##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-icon-theme
    - gcc
    - git
    - icon-naming-utils
    - imagemagick
    - inkscape
    - make
    - mate-common
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-icon-theme
    - git
    - icon-naming-utils
    - inkscape
    - imagemagick
    - intltool
    - librsvg2-bin
    - make
    - mate-common

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-icon-theme.git
    - gcc
    - git
    - icon-naming-utils
    - ImageMagick
    - inkscape
    - make
    - mate-common
    - redhat-rpm-config

  ubuntu:
    - git
    - icon-naming-utils
    - imagemagick
    - inkscape
    - intltool
    - librsvg2-bin
    - make
    - mate-common

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-icon-theme-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
